# fly.toml app configuration file generated for fragrant-meadow-6739 on 2023-10-25T18:50:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fragrant-meadow-6739"
primary_region = "waw"

[build]

[env]
PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
